env:
  browser: true
  es6: true
extends:
  - airbnb
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures: { jsx: true }
  ecmaVersion: 2020
  sourceType: module
rules:
  import/extensions: [error, ignorePackages]
  import/no-extraneous-dependencies: [error, { packageDir: "." }]
  jsx-a11y/label-has-associated-control: off
